version: '3.9'

services:
  db:
    container_name: db-zoomarket
    image: postgres:15
    volumes:
      - db-zoomarket:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    container_name: backend-zoomarket
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DEBUG=1

  frontend:
    container_name: frontend-zoomarket
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - DEBUG=1
  
  nginx:
    container_name: nginx-zoomarket
    image: nginx:1.25.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    ports:
      - "8000:8000"
      - "443:443"

volumes:
  db-zoomarket:
  