"""DataBase create

Revision ID: 2e53c8066370
Revises: 
Create Date: 2023-09-20 10:05:37.404365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e53c8066370'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=False),
        sa.Column('info', sa.Integer(), nullable=False),
        sa.Column('location', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories_pet',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('discount', sa.Float(), nullable=False),
        sa.Column('discounted_price', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stuff',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('categories_pet_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['categories_pet_id'], ['categories_pet.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desc_stuff',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('price_id', sa.Integer(), nullable=True),
        sa.Column('size', sa.String(), nullable=False),
        sa.Column('desc', sa.String(), nullable=False),
        sa.Column('brand_id', sa.Integer(), nullable=True),
        sa.Column('stuff_id', sa.Integer(), nullable=True),
        sa.Column('color_id', sa.Integer(), nullable=True),
        sa.Column('material_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
        sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
        sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
        sa.ForeignKeyConstraint(['price_id'], ['price.id'], ),
        sa.ForeignKeyConstraint(['stuff_id'], ['stuff.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('desc_stuff')
    op.drop_table('stuff')
    op.drop_table('price')
    op.drop_table('material')
    op.drop_table('color')
    op.drop_table('categories_pet')
    op.drop_table('brand')
    # ### end Alembic commands ###
