"""migration_new_base

Revision ID: 49e591d12ffa
Revises: 
Create Date: 2023-10-06 12:17:13.007780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e591d12ffa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('brand_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('info', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_table('categories',
    sa.Column('cat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_table('colors',
    sa.Column('color_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('color_id')
    )
    op.create_table('materials',
    sa.Column('mat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('mat_id')
    )
    op.create_table('prices',
    sa.Column('price_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('price_id')
    )
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=False),
    sa.Column('price_price_id', sa.Integer(), nullable=False),
    sa.Column('mat_mat_id', sa.Integer(), nullable=False),
    sa.Column('brand_brand_id', sa.Integer(), nullable=False),
    sa.Column('cat_cat_id', sa.Integer(), nullable=False),
    sa.Column('color_color_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_brand_id'], ['brands.brand_id'], ),
    sa.ForeignKeyConstraint(['cat_cat_id'], ['categories.cat_id'], ),
    sa.ForeignKeyConstraint(['color_color_id'], ['colors.color_id'], ),
    sa.ForeignKeyConstraint(['mat_mat_id'], ['materials.mat_id'], ),
    sa.ForeignKeyConstraint(['price_price_id'], ['prices.price_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('prices')
    op.drop_table('materials')
    op.drop_table('colors')
    op.drop_table('categories')
    op.drop_table('brands')
    # ### end Alembic commands ###
