"""new_migration_with_url_image

Revision ID: 79d2959176de
Revises: 49e591d12ffa
Create Date: 2023-10-06 18:21:45.664662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d2959176de'
down_revision: Union[str, None] = '49e591d12ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('url_image', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'url_image')
    # ### end Alembic commands ###
