"""create new table

Revision ID: f5f36a39bb61
Revises: 2e53c8066370
Create Date: 2023-09-28 18:15:13.812548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f36a39bb61'
down_revision: Union[str, None] = '2e53c8066370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brand', 'info',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('brand', 'location',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('desc_stuff', 'price_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('desc_stuff', 'size',
               existing_type=sa.Float(), 
               existing_nullable=False)
    op.alter_column('desc_stuff', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('desc_stuff', 'stuff_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('desc_stuff', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('desc_stuff', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stuff', 'categories_pet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stuff', 'categories_pet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('desc_stuff', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('desc_stuff', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('desc_stuff', 'stuff_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('desc_stuff', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('desc_stuff', 'size',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('desc_stuff', 'price_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('brand', 'location',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('brand', 'info',
               existing_type=sa.String(length=500),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
